.PHONY: all local

all:
	@cd src/frontend && npm install
	@cd src/frontend && npm run build
	@cd src && docker compose down
	@cd src && docker compose up -d --build

local:
	@cd src && docker compose down
	@cd src && docker compose up -d --build
	@cd src/frontend && npm install && npm run dev

test:
	@cd src/message-service && go test ./...
	@cd src/message-service && go test -tags=integration ./...
	@cd src/auth-service && go test ./...
	@cd src/auth-service && go test -tags=integration ./...
	@cd src/realtime-service && go test ./...
	@cd src/realtime-service && go test -tags=integration ./...
	@cd src/api-gateway && go test ./...
	@cd src/api-gateway && go test -tags=integration ./...
